client/js/items.js
Modified the message for more Loopring L2 feel.
=> add new loot message to replace rat burger with Layer 3 Taiko

client/js/npc.js
This reverts commit 426a4174361191471f1be7f79166895c7bbe71e0.
=> Revert "add new npc messages for Loopring L2 feel (#136)"

client/js/npc.js
This one seems to work... (fingers crossed)
=> Npc new text

server/js/nftweapon.js, server/js/player.js, server/js/worldserver.js
This reverts commit 4ce73c4c7e587a1b5e0d027e3d26047f7ba74236.
=> Revert "More frequent xp changes (#276)"

server/js/nftweapon.js, server/js/player.js, server/js/worldserver.js
This reverts commit c699bed0e36779ce7f2af1d99c6694c828a51db1.
=> Revert "More frequent xp changes (#279)"

server/js/nftweapon.js, server/js/player.js, server/js/worldserver.js
This reverts commit 03bd76d194e4631aa15fcdd8c978202f87995071.
=> Revert "More frequent xp changes (#281)"

client/js/main.js
=> updated credits

client/js/game.js, client/js/storage.js, server/js/player.js, server/js/ws.js
This reverts commit b752d372893ee28c0a234e374d7fef0d5e80d6f7.
=> Revert "Restore xy (#315)"

server/js/properties.js, server/js/worldserver.js
=> On death aoe dmg property

server/js/formulas.js, server/js/mob.js, server/js/worldserver.js
Added shared EXP handling on mob kill.
=> Added shared EXP

client/js/keyboardhandler.js
- WASD is now handled on an interval started with keydown and cleared with keyup, which means no more delays on first step and being dependant on OS key repeat settings
- Changed a bit the way logic works, instead of checking exactly whether w/a/s/d is pressed and moving, we add a value from each key and then execute one click which is a sum of all the buttons. This greatly improves the way the game behaves when more than one button is pressed (allows for smooth diagonal movement etc.)
=> Keyboard handler improvements

client/js/game.js, server/js/worldserver.js, server/js/ws.js
- Fixed an issue where other players dissapeared (client side) when stepping on inactive doors
- Fixed an issue where other players dissapeared (client side) when stepping on tokenized doors (that they didnt have an NFT for)
=> Trig door others upd

client/js/main.js
=> Disabled ESC button pausing the mobs

tools/maps/processmap.js
Fixed processmap code for object-layers with a single object, as layer.object is not an array in that case.
I refactored the code for extendability/readability while I was at it.
This change is needed as I can't compile a map with less than two objects in some object-layers.
=> Fixed processmap for object-layers with a single object

client/js/character.js
keep flipping the character for left-animations, so the weapon won't be flipped.
=> Fix left-animation when character holds weapon

client/js/character.js, client/js/game.js, client/js/gameclient.js, client/js/map.js, server/js/area.js, server/js/format.js, server/js/map.js, server/js/player.js, server/js/worldserver.js, shared/js/gametypes.js, tools/maps/processmap.js
This reverts commit 3cb48f1761db3f148942ec4825399ddeac372e23.
=> Revert "Trigger areas & Negative trigger activated doors (#453)"

client/js/npc.js
changed the text that my npc displays.
=> cobmin npc change

client/js/game.js, client/js/map.js, server/js/ws.js
Let's map-makers add a "quest" property to doors.
Also an optional "quest_message" is added to  doors to display a custom-message when the door is locked by a quest.
When a quest property is set, players can only enter a door if the quest is completed.
=> Added quest-gated-doors

client/css/main.css
=> fix health-bar style for mobile

server/js/item.js, server/js/properties.js
Added optional respawnDelay property to static items - default remains 30s
=> Added respawnDelay property to items

Dockerfile, Dockerfile.prod
It appears that a recent version of bun broke WS
=> Revert to node js

client/js/keyboardhandler.js, client/js/player.js
Added keyboard control to loop over weapons..
Use  < , > (Comma) and < . > (Period) to go through the weapons
=> cycle through weapons

client/js/game.js
Steps to reproduce on production:
1. Start session.
2. Press 'enter' to open chat
3. Press 'esc' to close chat
4. Error appears and player character won't move on keyboard nav.
=> Fix errors causing player to freeze.

client/js/keyboardhandler.js
added checks to make sure the player has no open dialog or has an input field on focus.
=> Check for open dialogs/active input when listening to keyboard input

server/js/discord.js
DO NOT MERGE UNTIL NOV 1st 2023
=> disable loopworms chat

client/js/app.js, server/js/worldserver.js
- inventory bug fix (rarely happened)
- megamag fix where sometimes field effects stayed on the floor after boss reseted/got killed
=> iterate in a backwards loop when doing splices

client/js/game.js, client/js/infomanager.js, server/js/dao.js, server/js/lakes.js, server/js/nftspecialitem.js, server/js/player.js, server/js/quests/playereventbroker.js, server/js/ws.js
- fixed a bug where a consumable fish would be awarded twice
- added 3 fishing traits:
* lucky -> % chance to get better fish (rolls twice and gets the better outcome)
* upper hand -> % chance to have double the green area, making fish significantly easier to catch
* double catch -> % chance that a fish you catch gets awarded twice
=> fishing traits added, double consumable bug fixed

client/css/achievements.css, client/js/app.js, client/js/main.js
=> fix quest-log navigation

client/js/gameclient.js, server/js/flows/mapflow.js
=> Fix quest tracking

client/css/main.css, client/index.html, client/js/app.js, client/js/game.js, client/js/main.js
=> move player & weapon stats

server/js/player.js, server/js/quests/playereventbroker.js
=> fixed track item count

client/css/main.css, client/index.html, client/js/app.js, client/js/game.js, client/js/gameclient.js, server/js/format.js, server/js/lakes.js, server/js/player.js, server/js/ws.js
Bullseye when you catch a fish exactly in the middle of the green zone => +50% exp gained.
Minor refactors and improvements to fishing
=> bullseye + minor fishing refactors

client/css/main.css, client/js/app.js, server/js/collectables.js, server/js/lakes.js, server/js/player.js, server/js/properties.js, server/js/ws.js
- When you eat another fish of the same stat and %, the duration increases (stacks) instead of refreshing, up to 60 min
- Buff stat preview in the inventory (general method to add consumable inventory description, works with other consumes too)
=> stack buff duration, inventory buff preview

server/js/dao.js
Consumable counts cleared normal loot event counts.
=> fix loading item counts

client/sprites/NFT_000065cd331fea3429d8c73f7315a83a7f611692df70d0624db863904bdc8cde.json
Part of the float project ticket
=> Float for bitcorn - json for proper dimensions to existing sprite

client/js/game.js, client/js/renderer-webworker.js, client/js/renderer.js
=> Draw the cursor using the high canvas

client/css/main.css, client/index.html, client/js/app.js, client/js/main.js, client/js/settings.js
Simplest solution to full-screen I could think of
=> fullscreen

client/sprites/NFT_0dfa5c65d2738a1e16a231a409b047396e6fc2b7d3b4ad5171a8f133adf5134b.json
=> Playerboss 20231217 3

client/css/ie.css, client/css/main.css, client/index.html, client/js/app.js, client/js/game.js, client/js/keyboardhandler.js, client/js/main.js
=> inventory UI

client/css/main.css
Removed till we have a consistent solution for custom checkbox styling
=> checkbox border doesn't work good on all devices.

client/css/main.css, client/index.html, client/js/main.js, client/js/touchListener.js
You can now use your screen as a virtual thumb-stick
=> added touch-control

server/js/flows/mapflow.js, server/js/flows/worldfloweventconsumer.js
=> fix double event listeners when players respawned

client/js/game.js, client/js/keyboardhandler.js, client/js/renderer.js, client/js/sprite.js
=> fix highlighting & space-to-engage

client/sprites/NFT_28f54474dd8c62c98964e998e4b77c2d5f0dee1aaeda3afa52bb96b064fce533.json, client/sprites/NFT_64f2fc753b07443aea04be793a117e8ae53a3d312d1593ede209d56a647a8492.json
Updated json for CyberCrew companions
=> modified CyberCrew spritesheets

shared/js/gametypes.js
NPC fix, got removed by accident about 2 weeks ago
=> added missing line that resulted in the npc dissapearing

server/js/entity.js, server/js/worldserver.js
2 main changes:
A) Removed probable infinite loop
B) Now we only do a check max. 4 times (N S W E), because each side is checked only once (as opposed to checking the same coords few times, based on random)
=> Find position refactor

client/sprites/NFT_0178a0c8e20623d352ca3a36a61dad8fe93919139dd89c318eaaf674bc7edf17.json
=> modified nancy player boss

client/js/game.js, client/js/map.js
don't show message if someone else triggers the  message
=> Personal trigger messages

client/js/character.js, client/js/game.js
Fix for PvP with ranged weapon
Fix for opening chests with ranged weapon
=> Fix ranged weapon pvp

client/sprites/NFT_686bee99e15e71659a960a9614816fc97a983e5cb769580267478a3d9dffe850.json
Just change to a Looper JSON to make a boss playable for the event.
=> Made valentyne boss playable Looper - simple json change

server/js/flows/mapflow.js
=> fix trigger.deactivated map-flow event

client/sprites/NFT_1eb7bc40ba929c8e7b0cbc2b3b74c19a448342fdaaa4d8df13bda2a83bb52612.json, client/sprites/NFT_230417bedebae0940f547b1d533342f3db136129c497819e9a80e7cd4a594b92.json, client/sprites/NFT_3126874850522c78e918aad1b2d853812b1f4b1f9f86a9917a0df9377f4584e9.json, client/sprites/NFT_3417d55efa9f8d531c34a390fbee557d61c60f91439653c755b1ec12401392ec.json, client/sprites/NFT_5e6bc91e5bc6c95d5c736cebd4c6f58712b74832d3a152a1ffbbe8044d07358c.json, client/sprites/NFT_62f4d608ebad5d4b2fafb8db19a6eadb82739d262c02c10384bbd079fb39dd55.json, client/sprites/NFT_64f2fc753b07443aea04be793a117e8ae53a3d312d1593ede209d56a647a8492.json, client/sprites/NFT_6d5ca230e96b8b8abb05bf80757ee63700347c5bec1ce8a1f24847c029dfd7dc.json, client/sprites/NFT_8b1d457cd11e43b6a627b2f5e5d45fe724ac1c0805951a54856bced7c0d6bdb9.json, client/sprites/NFT_929cce2e50749991230410f45e39abaf97eb25d3bed4e67a49c245dbc15ca4f3.json, client/sprites/NFT_9c4a089926b66f4933c1d497654656794105f98c1e46676b7d183f06b6a769bf.json, client/sprites/NFT_a481b37bd3d0680b321501cfe3ffe7cc8d3a7e1a7cda952ca885dcbb1fba5165.json, client/sprites/NFT_ab9bcf29717f044773bd4a620370d05446c7b83cb2f3a800521e2f400b6c1187.json, client/sprites/NFT_afe62b08af1bebe0ae6e4b08117513e280c4eba035a3352a2710460939e6a008.json, client/sprites/NFT_bc422520eda8d02cd5b0a5270645e87660d0e0f0e062fe6397fabf38e7ad93c0.json, client/sprites/NFT_f20d4a9c3feb2749a62b7a71e1a890161533ca067b69feb4d91e6289ac9da271.json, client/sprites/NFT_f58bf2da698c74299e4c4e154d117e1304abc0deaf0469570a4122675a8eab7f.json, client/sprites/NFT_f94e13a3cdaa49b1a86348ec5740768665702c66d7096caefb5f14a54ac38ae1.json, client/sprites/NFT_fc5dba7f589fdad6e5bcf74da24d7fb0cdef89096a1a25eed51c75f107f5433b.json
Updated the spritesheet json for new (more complex) Icerend companions and fixed the CC palantir beetle
=> Modified json for OA companions - more frames/dimensions

client/js/npc.js, server/js/properties.js
DIMMIE EGG, oni boss and other things
=> minor egg hunt updates

client/apps/luckyfunkz/js/luckyfunkz.js, server/apps/luckyfunkz/luckyfunkz.js, server/js/dao.js, server/js/ws.js
**ws.js**
workover getSpin
**dao.js** 
saveLootEvent cleanups, add saveMultiLootEvent, add await for forced call of processLootEventQueue, adjust updateResourceBalance to allow group of transactions, simplify transferResourceFromTo
**luckyfunkz.js** _client side_
autospinbutton minor cleanup
**luckyfunkz.js** _server side_ 
remove dao calls, fix payout * betperline, cleanup
=> LuckyFUNKZ patch

client/js/game.js, server/js/dao.js, server/js/formulas.js, server/js/inventorysynccontroller.js, server/js/inventorysynccontroller.test.js, server/js/player.js, server/js/ws.js
```
curl -X POST http://localhost:8000/inventorysync      -H "Content-Type: application/json"      -d '{"nftId": "0xd1570dc356007d297c8ee63716d38d264a621516f44e3305839fc29ca36e2ce2"}' -H "x-api-key: placeholder"
```
=> Inventory sync controller

.github/workflows/deploy.yml
This reverts commit 3810bda0a15788b7953da7b221670abdb7849e69.
=> Revert "Disable hostinger deploy (#1130)"

server/js/quests/main.js, server/js/quests/playerquesteventconsumer.js
Added optional item as quest reward
=> optional item reward

server/js/quests/oa.js
Added text for in progress & requirement of returning to NPC's upon finishing quests as well as updated end text
=> Everloop - Quest text updates / return to NPC

server/js/looperlandsplatformclient.js, server/js/looperlandsplatformclient.spec.js
Changed endpoint to include server-level modifiers
=> changed endpoint to include server-level modifiers

client/js/game.js, client/js/main.js
This reverts commit 582ffee14df4e9a13ed08073cbedbcfc6663a08f.
=> Revert "only allow one item per grid square (#1291)"

client/js/game.js
Fix for mouse nav
And first try to improve scene-loading.
=> Fix for mouse-nav
